import { NextResponse } from "next/server";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { requirePcmUser } from "@/app/api/management/tokens/_lib/auth";
import { decodeRouteParam } from "@/lib/decodeRouteParam";
import { normalizeCnpj } from "@/lib/cnpj";
import { excelDateNumberToMillis, parseXlsxTable } from "@/lib/xlsxParser";
import { getAdmin } from "@/lib/firebaseAdmin";
import { buildServiceImportKey, findServicesByImportKeys } from "@/lib/repo/services";
import { createPackageFolder, listPackageFolders } from "@/lib/repo/folders";
export const runtime = "nodejs";
const n=(v:unknown)=>String(v??"").trim();
const pick=(r:Record<string,unknown>,k:string[])=>k.map((x)=>r[x]).find((x)=>x!=null&&String(x).trim())??null;
const d=(v:unknown)=>typeof v==="number"?excelDateNumberToMillis(v):(Number.isFinite(Date.parse(n(v)))?Date.parse(n(v)):null);
const h=(v:unknown)=>{const x=Number(String(v??"").replace(",","."));return Number.isFinite(x)&&x>0?x:0;};
export async function POST(req:Request,ctx:{params:{packageId:string}}){await requirePcmUser(req);const packageId=decodeRouteParam(ctx.params.packageId||"").trim();if(!packageId)return NextResponse.json({ok:false,error:"packageId inválido"},{status:400});const formData=await req.formData();const file=formData.get("file");if(!(file instanceof File))return NextResponse.json({ok:false,error:"Envie o arquivo."},{status:400});const rows=parseXlsxTable(await file.arrayBuffer(),8);const parsed=[] as any[];for(const row of rows){const os=n(pick(row,["O.S","OS"]));const tag=n(pick(row,["TAG MAQUINA","TAG","TAG MÁQUINA"]));const equipamento=n(pick(row,["EQUIP. NOVO","EQUIPAMENTO NOVO","EQUIPAMENTO"]));const empresa=n(pick(row,["EMPRESA"]));const cnpj=normalizeCnpj(n(pick(row,["CNPJ","C.N.P.J."])))||null;const inicio=d(pick(row,["DATA DE INICIO","DATA DE INÍCIO","INICIO"]));const fim=d(pick(row,["DATA FINAL","DATA FIM","FIM"]));const horas=h(pick(row,["TOTAL DE HORA HOMEM","TOTAL HORA HOMEM"]));const setor=n(pick(row,["SETOR"]))||null;if(!os||!tag||!equipamento||!inicio||!fim||!horas)continue;const importKey=await buildServiceImportKey({os,tag,setor,equipmentName:equipamento,plannedStart:inicio,plannedEnd:fim,empresa:empresa||null,cnpj});parsed.push({os,tag,equipamento,empresa:empresa||"Sem empresa",cnpj,inicio,fim,horas,setor,importKey});}
const folders=await listPackageFolders(packageId);const byCompany=new Map(folders.map((f)=>[f.name.trim().toLowerCase(),f]));let foldersCreated=0;for(const company of Array.from(new Set(parsed.map((p)=>p.empresa.trim().toLowerCase())))){if(!company||byCompany.has(company))continue;const raw=parsed.find((p)=>p.empresa.trim().toLowerCase()===company);const created=await createPackageFolder({packageId,name:raw.empresa,companyId:raw.cnpj??undefined});byCompany.set(company,created);foldersCreated++;}
const existing=await findServicesByImportKeys(parsed.map((p)=>p.importKey));const existingMap=new Map(existing.map((s)=>[s.importKey,s]));const db=getAdmin().db;let created=0,updated=0;for(const item of parsed){const folder=byCompany.get(item.empresa.trim().toLowerCase());const found=existingMap.get(item.importKey);const payload={os:item.os,tag:item.tag,equipamento:item.equipamento,equipmentName:item.equipamento,setor:item.setor,inicioPrevisto:Timestamp.fromMillis(item.inicio),fimPrevisto:Timestamp.fromMillis(item.fim),horasPrevistas:item.horas,company:item.empresa,empresa:item.empresa,empresaId:item.empresa,cnpj:item.cnpj,importKey:item.importKey,packageId,pacoteId:packageId,folderId:folder?.id??null,subpackageId:folder?.id??null,updatedAt:FieldValue.serverTimestamp()};if(found?.id){await db.collection("services").doc(found.id).set(payload,{merge:true});updated++;}else{await db.collection("services").doc().set({...payload,status:"Aberto",createdAt:FieldValue.serverTimestamp(),createdBy:"pcm"});created++;}}
return NextResponse.json({ok:true,created,updated,skipped:Math.max(0,rows.length-parsed.length),foldersCreated});}
