import type { Metadata } from "next";
// @ts-ignore: allow global CSS side-effect import without type declarations
import "./globals.css";
import PreloadAsFix from "@/components/PreloadAsFix";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="antialiased">
        <PreloadAsFix />
        {children}
      </body>
    </html>
  );
}
